#!/usr/bin/env python3
"""Generate a short, concise, detailed DOCX vignette of how Quasar works.

Produces docs/quasar_vignette.docx with:
  - 1-paragraph what-it-is
  - Flow diagram (PNG generated by matplotlib + embedded)
  - Per-step algorithm summary
  - Benchmark headline numbers
  - Key innovations not in any general-purpose caller
"""
from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from docx import Document
from docx.shared import Cm, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

PROJECT = Path(__file__).resolve().parent.parent
DOCS = PROJECT / "docs"


def make_flow_diagram(out_path: Path) -> None:
    """Render the 12-step Quasar pipeline as a clean flow diagram."""
    fig, ax = plt.subplots(figsize=(10, 11))
    ax.set_xlim(-1.5, 10.5)
    ax.set_ylim(0, 22)
    ax.axis("off")

    # House style — dark navy + accents
    navy = "#16213e"
    accent_red = "#d62728"
    accent_blue = "#3b82f6"
    accent_green = "#16a34a"
    light_grey = "#f1f5f9"
    text_white = "white"

    steps = [
        ("INPUT",              "BAM / CRAM   +   caller VCFs (Manta / GRIDSS / Delly / SvABA / TIDDIT / FACTERA)", navy,       text_white, 21.0),
        ("1.  pysam scan",     "~40 driver + IG/TR + artefact loci  ·  SR (split-read) + PE (discordant)",         accent_blue, text_white, 19.0),
        ("2.  Artefact rescue",  "Reverse-scan chr2:32916 polyG attractor  ·  recover IG-switch reads it eats",     accent_red,  text_white, 17.5),
        ("3.  Parse caller VCFs", "Normalise each tool's BND/DEL/DUP/INV to BreakpointCall schema",                   accent_blue, text_white, 16.0),
        ("4.  Evidence merge",  "Cluster across callers @ ±250 bp  ·  SUM independent evidence TYPES, not votes",   navy,       text_white, 14.5),
        ("5.  Tier rules",      "T1/T2/T3 from multi-caller × multi-ev-type × PASS × precise  ·  single-caller T1 only via SR≥10 + PE≥10",  navy, text_white, 12.7),
        ("6.  Annotate",        "Gene assignment + driver_locus + known_partner from lymphoma_loci + known_partners", accent_blue, text_white, 11.0),
        ("7.  QC flags",        "Artefact mask (auto T3)  ·  recurrent-position  ·  short-range (aSHM-aware)",         navy,       text_white, 9.5),
        ("8.  IG-driver rescue", "Lineage prior (B / T)  ·  canonical IG alternatives  ·  ig_partner_ambiguous flag", accent_red, text_white, 8.0),
        ("9.  Canonical promote", "known_partner pair + ≥5 evidence → ≥T2  ·  strong SR/PE → T1",                      accent_green, text_white, 6.5),
        ("10. Event classify",  "IG_intra · IG_IG · IG_driver_canonical · IG_driver_novel · driver_driver · driver_intra · …", navy, text_white, 5.0),
        ("11. Demote non-clinical T1", "V(D)J + intra-driver aSHM + recurrent-artefact T1 → T3 (unless multi-caller PASS)",  navy, text_white, 3.5),
        ("OUTPUT",              "FusionCall TSV + JSON  ·  brochure HTML  ·  cohort dashboard  ·  VCF 4.3 (emit-vcf)",  navy,       text_white, 1.8),
    ]

    box_h = 1.05
    arrow_y_offset = -0.55

    for i, (label, detail, fill, fg, y) in enumerate(steps):
        # Two-line box: bold label + detail
        rect = mpatches.FancyBboxPatch(
            (0.6, y - box_h / 2), 8.8, box_h,
            boxstyle="round,pad=0.04,rounding_size=0.12",
            linewidth=0,
            facecolor=fill, edgecolor=fill, alpha=0.96,
        )
        ax.add_patch(rect)
        ax.text(5.0, y + 0.18, label, ha="center", va="center",
                fontsize=11, fontweight="bold", color=fg)
        ax.text(5.0, y - 0.21, detail, ha="center", va="center",
                fontsize=8.0, color=fg)

        # Arrow to next box
        if i < len(steps) - 1:
            next_y = steps[i + 1][4]
            ax.annotate(
                "", xy=(5.0, next_y + box_h / 2 + 0.02),
                xytext=(5.0, y - box_h / 2 - 0.02),
                arrowprops=dict(arrowstyle="-|>", lw=1.4, color="#94a3b8",
                                shrinkA=0, shrinkB=0),
            )

    # Side annotation — what makes this lymphoma-specific
    ax.text(-1.3, 10.5, "lymphoma-aware\nlayers\n(no other tool\nhas these)",
            fontsize=8.5, color=accent_red,
            ha="left", va="center", fontweight="bold", rotation=0)
    # Bracket the lymphoma-specific layers (2, 7, 8, 9, 10, 11)
    ax.plot([0.4, 0.4], [3.0, 18.0], color=accent_red, lw=1.5)
    ax.plot([0.4, 0.55], [18.0, 18.0], color=accent_red, lw=1.5)
    ax.plot([0.4, 0.55], [3.0, 3.0], color=accent_red, lw=1.5)

    fig.savefig(out_path, dpi=160, bbox_inches="tight", facecolor="white")
    plt.close(fig)


def _set_cell_bg(cell, hex_color: str) -> None:
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:fill"), hex_color)
    tc_pr.append(shd)


def add_h1(doc, text):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.font.size = Pt(20)
    r.font.bold = True
    r.font.color.rgb = RGBColor(0x16, 0x21, 0x3e)


def add_h2(doc, text):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.font.size = Pt(13)
    r.font.bold = True
    r.font.color.rgb = RGBColor(0x16, 0x21, 0x3e)


def add_body(doc, text, italic=False, size=10.5):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.font.size = Pt(size)
    r.italic = italic


def add_bullet(doc, text):
    p = doc.add_paragraph(style="List Bullet")
    r = p.add_run(text)
    r.font.size = Pt(10.5)


def make_docx(out_path: Path, flow_image: Path) -> None:
    doc = Document()

    # Page margins
    for section in doc.sections:
        section.left_margin = Cm(2.0)
        section.right_margin = Cm(2.0)
        section.top_margin = Cm(2.0)
        section.bottom_margin = Cm(2.0)

    # Title block
    add_h1(doc, "Quasar")
    sub = doc.add_paragraph()
    r = sub.add_run("Lymphoma structural-variant + fusion detection — algorithm vignette")
    r.font.size = Pt(11)
    r.font.color.rgb = RGBColor(0x4b, 0x55, 0x63)
    r.italic = True

    # One-paragraph summary
    add_h2(doc, "What it is")
    add_body(doc, (
        "Quasar is an open-source, ensemble structural-variant caller for lymphoma "
        "next-generation sequencing — both targeted panels and whole-genome. It consumes BAM/CRAM "
        "directly (its own pysam scanner) and/or VCFs from Manta, GRIDSS, Delly, SvABA, TIDDIT, "
        "and FACTERA, then runs a 12-step lymphoma-aware pipeline that produces tiered fusion "
        "calls, per-sample clinical brochures, a cohort dashboard, and a VCF 4.3 export. "
        "Designed for clinical deployment, anti-paywall, patient-care first."
    ))

    # Headline benchmark
    add_h2(doc, "Headline benchmark (14-sample WGS cohort, 4-tool head-to-head)")
    table = doc.add_table(rows=6, cols=4)
    table.style = "Light Grid Accent 1"
    hdr = table.rows[0].cells
    for i, h in enumerate(("Tool", "Precision", "Recall", "F1")):
        hdr[i].text = h
        hdr[i].paragraphs[0].runs[0].font.bold = True
        _set_cell_bg(hdr[i], "16213e")
        hdr[i].paragraphs[0].runs[0].font.color.rgb = RGBColor(0xff, 0xff, 0xff)

    rows = [
        ("Quasar",   "0.87", "0.81", "0.84"),
        ("Manta 1.6.0",   "0.71", "0.38", "0.50"),
        ("Delly 2.1.0",   "0.43", "0.21", "0.29"),
        ("SvABA 1.2.0",   "0.14", "0.21", "0.17"),
        ("TIDDIT 3.9.5",  "0.00", "0.00", "0.00"),
    ]
    for r_idx, vals in enumerate(rows, start=1):
        for c_idx, v in enumerate(vals):
            cell = table.rows[r_idx].cells[c_idx]
            cell.text = v
            cell.paragraphs[0].runs[0].font.size = Pt(10)
            if r_idx == 1:
                cell.paragraphs[0].runs[0].font.bold = True
                _set_cell_bg(cell, "dbeafe")

    add_body(doc,
             "GRIDSS 2.13.2 not in the table — its setup ran ~12 hr/sample on this hardware "
             "and was killed; the lymphoma blind spot (PMBL polyG attractor) is shared with the "
             "other general-purpose callers.", italic=True, size=9)

    # Page break before flow diagram
    doc.add_page_break()

    add_h2(doc, "Algorithm flow")
    add_body(doc,
             "Twelve steps from CRAM to clinical report. Red-bracketed boxes are the layers "
             "no general-purpose SV caller has — every other tool stops at step 5.", size=10)
    doc.add_picture(str(flow_image), width=Cm(17))
    cap = doc.add_paragraph()
    r = cap.add_run("Source: src/quasarsv/{scanners,merge,annotate,qc,rescue,classify,promote}.py")
    r.font.size = Pt(8.5)
    r.italic = True
    cap.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Page break before key innovations
    doc.add_page_break()

    add_h2(doc, "Four structural advantages no general-purpose caller has")

    add_body(doc, "1. polyG-attractor rescue (step 8)", size=11)
    add_body(doc,
             "PMBL t(3;14) chimeric reads have their IGH side absorbed by the chr2:32916 polyG "
             "stretch in GRCh38 (>644 k reads per sample). General-purpose callers see a "
             "BCL6↔chr2 BND and stop. Quasar synthesises the underlying BCL6-IGH translocation "
             "from the artefact-mediated signal, with a B-cell lineage prior + canonical-partner "
             "promotion. Uniquely catches both PMBL samples in the benchmark.")

    add_body(doc, "2. Canonical-partner tier promotion (step 9)", size=11)
    add_body(doc,
             "A 30-row known_partners.tsv table covers every clinically-actionable lymphoma "
             "translocation (IGH-MYC, IGH-BCL2, IGH-BCL6, IGH-CCND1, NPM1-ALK, BCL6 promiscuous "
             "partners, etc.) tagged with disease. Any annotated pair with ≥5 SR or ≥10 PE is "
             "promoted to T1 — catches MD903 BCL6-IGH and NU-DUL-1 MYC-IGH where Manta records "
             "exist but score 0 against its own quality filter.")

    add_body(doc, "3. Evidence-level merge, not caller-vote (step 4)", size=11)
    add_body(doc,
             "Two callers seeing the same split-read cluster counts as one piece of evidence, "
             "not two. The merger sums independent evidence types (split read, discordant pair, "
             "assembly contig, soft clip) at ±250 bp tolerance and tiers on that. Avoids the "
             "false-positive explosion that hits Delly (4 FPs) and SvABA (18 FPs) when caller-vote "
             "agreement isn't filtered for evidence-type independence.")

    add_body(doc, "4. Lymphoma-aware event classification + demotion (steps 10-11)", size=11)
    add_body(doc,
             "Every call is classed as IG_intra (V(D)J), IG_IG (noise), IG_driver_canonical "
             "(clinical), IG_driver_novel (review), driver_driver (clinical), driver_intra (aSHM), "
             "or intergenic. Single-caller T1 calls that fall into the non-clinical buckets are "
             "demoted to T3 unless multi-caller PASS preserves them. This is what gives Quasar "
             "precision = 0.87 while every general-purpose caller's precision is ≤0.71.")

    # Reproduce + scope
    add_h2(doc, "How to reproduce in one command")
    add_body(doc,
             "cd <project_root> && pytest tests/ -q && \\\n"
             "quasar benchmark "
             "output/wgs_cohort/*/*.fusions.tsv --relax-canonical-ig-partner", size=9)

    add_h2(doc, "Scope")
    add_bullet(doc, "Inputs: BAM/CRAM and/or VCFs from any subset of Manta, GRIDSS, Delly, SvABA, TIDDIT, FACTERA")
    add_bullet(doc, "Outputs: FusionCall TSV/JSON · per-sample brochure HTML · cohort dashboard · VCF 4.3")
    add_bullet(doc, "Cohort tested: 23 lymphoma WGS samples (PMBL, DLBCL, ATLL, T-cell NHL, Immunodef NHL)")
    add_bullet(doc, "Tests: 51 passing")
    add_bullet(doc, "Source: src/quasarsv/  ·  docs/algorithm_vignette.md  ·  docs/benchmark_results.md")
    add_bullet(doc, "Open source, anti-paywall — designed for clinical deployment, patient-care first")

    doc.save(str(out_path))


if __name__ == "__main__":
    DOCS.mkdir(parents=True, exist_ok=True)
    flow_png = DOCS / "quasar_flow.png"
    make_flow_diagram(flow_png)
    print(f"[diagram] {flow_png}")
    docx_out = DOCS / "quasar_vignette.docx"
    make_docx(docx_out, flow_png)
    print(f"[docx]    {docx_out}")
